-- Productos de muestra para ver el catálogo armado. Se pueden editar o borrar desde el panel.
insert into public.products (id, position, visible, data) values
  ('m-iphone-18-pro', 0, true, '{"id":"m-iphone-18-pro","name":"iPhone 18 Pro","brand":"Apple","category":"Celulares","description":"","specs":["6,3\"","Cámara 48 MP","A20 Pro"],"badge":"","isNew":true,"visible":true,"colors":[{"name":"Black","hex":"#1F2022","images":[]},{"name":"Burgundy","hex":"#6A3348","images":[]},{"name":"Silver","hex":"#DFE1E4","images":[]},{"name":"Glacier","hex":"#7693BE","images":[]}],"variants":[{"label":"256 GB","price":1650,"priceSale":null,"inStock":true},{"label":"512 GB","price":1850,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-iphone-17-pro-max', 1, true, '{"id":"m-iphone-17-pro-max","name":"iPhone 17 Pro Max","brand":"Apple","category":"Celulares","description":"","specs":["6,9\"","Cámara 48 MP"],"badge":"","isNew":false,"visible":true,"colors":[{"name":"Cosmic Orange","hex":"#EE7A3E","images":[]},{"name":"Deep Blue","hex":"#33486B","images":[]},{"name":"Silver","hex":"#DFE1E4","images":[]}],"variants":[{"label":"256 GB","price":1370,"priceSale":1320,"inStock":true}]}'::jsonb),
  ('m-iphone-17', 2, true, '{"id":"m-iphone-17","name":"iPhone 17","brand":"Apple","category":"Celulares","description":"","specs":["6,3\"","Cámara 48 MP"],"badge":"","isNew":false,"visible":true,"colors":[{"name":"Sage","hex":"#B4BE96","images":[]},{"name":"Black","hex":"#1F2022","images":[]}],"variants":[{"label":"256 GB","price":1020,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-macbook-neo', 3, true, '{"id":"m-macbook-neo","name":"MacBook Neo","brand":"Apple","category":"Notebooks","description":"","specs":["13\" Liquid Retina","A18 Pro"],"badge":"","isNew":true,"visible":true,"colors":[{"name":"Citrus","hex":"#D9E26B","images":[]},{"name":"Silver","hex":"#DFE1E4","images":[]}],"variants":[{"label":"256 GB","price":850,"priceSale":null,"inStock":true},{"label":"512 GB","price":950,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-airpods-4', 4, true, '{"id":"m-airpods-4","name":"AirPods 4","brand":"Apple","category":"Audio","description":"","specs":["Estuche USB-C","Audio espacial"],"badge":"","isNew":false,"visible":true,"colors":[{"name":"Blanco","hex":"#F2F2F0","images":[]}],"variants":[{"label":"Estándar","price":200,"priceSale":null,"inStock":true},{"label":"Con cancelación de ruido","price":250,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-ps5-slim', 5, true, '{"id":"m-ps5-slim","name":"PlayStation 5 Slim","brand":"Sony","category":"Gaming","description":"","specs":["825 GB SSD","4K"],"badge":"Digital","isNew":false,"visible":true,"colors":[{"name":"Blanco","hex":"#F2F2F0","images":[]}],"variants":[{"label":"Digital","price":750,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-jbl-charge-6', 6, true, '{"id":"m-jbl-charge-6","name":"JBL Charge 6","brand":"JBL","category":"Audio","description":"","specs":["45 W","28 h de batería","IP68"],"badge":"","isNew":false,"visible":true,"colors":[{"name":"Black","hex":"#1F2022","images":[]}],"variants":[{"label":"","price":170,"priceSale":null,"inStock":true}]}'::jsonb),
  ('m-xiaomi-s40', 7, true, '{"id":"m-xiaomi-s40","name":"Xiaomi Robot Vacuum S40","brand":"Xiaomi","category":"Hogar","description":"","specs":["Aspira y trapea","Navegación láser"],"badge":"","isNew":false,"visible":true,"colors":[{"name":"Black","hex":"#1F2022","images":[]},{"name":"Blanco","hex":"#F2F2F0","images":[]}],"variants":[{"label":"","price":230,"priceSale":null,"inStock":true}]}'::jsonb)
on conflict (id) do nothing;
